name: Weixin

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run deployment script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          python main.py
