name: weixin
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Set environment variables from GitHub Secrets
        run: |
          # 确保 base64 输出为一行，并正确设置环境变量
          echo "CONFIG=$(echo -n \"$CONFIG\" | base64)" >> $GITHUB_ENV
        env:
          CONFIG: ${{ secrets.CONFIG }}

      - name: Run the Python script
        run: python3 main.py
